apiVersion: v1
kind: Service
metadata:
  name: {{ template "tarantool.fullname" . }}
  labels:
    app: {{ template "tarantool.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: tarantool
    port: 3301
    targetPort: 3301
  - name: tarantool-admin
    port: 3302
    targetPort: 3302
  selector:
    app: {{ template "tarantool.fullname" . }}
